[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["Poseidon2", "Poseidon2Yul", "Poseidon2Huff"]
ffi = true
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "screaming-snake-case-const"]

[fuzz]
runs = 10000
max_test_rejects = 0